### ISSUE TITLE
Feature request: scaling

### ISSUE THREAD

**Issue by LaptopDev** [zigalenarcic/mangl#12]
My high-dpi monitor makes the app too small to use 
![mangl-too-small](https://github.com/zigalenarcic/mangl/assets/6458102/4e7f0b5b-3cf2-4704-a18b-46224222521d)

**Comment by zigalenarcic** [comment]
Hi
Please try to use settings in .manglrc and see if it solves the issue (see mangl's manpage).

**Comment by LaptopDev** [comment]
> Hi Please try to use settings in .manglrc and see if it solves the issue (see mangl's manpage).

Thank you, I got this wonderful utility working at scale now in wayland :)

'font: Anonymous Pro
font_size: 10
gui_scale: 1.5
...
initial_window_rows: 28'
