### ISSUE TITLE
[Feature Request] XDG Base Directory Support

### ISSUE THREAD

**Issue by Rayqan** [zigalenarcic/mangl#14]
Would you consider adding XDG Base Directory Support for the manglrc file as defined in https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html.

**Comment by zigalenarcic** [comment]
In commit d0f7f3a4cfa243296d2c7f16605f95ed4dd4dca3 I added reading of config files:
$XDG_CONFIG_HOME/mangl/manglrc
~/.config/mangl/manglrc

I don't know if this satisfies the specification completely and in general I observe that these locations are used when applications themselves write their configuration. mangl doesn't write its configuration currently so configuration file is always written by the user but I hope these new file locations help with organisation.

**Comment by Rayqan** [comment]
Yep that it perfect. Thanks!
