### ISSUE TITLE
Make warnings and no back option

### ISSUE THREAD

**Issue by zeroidentidad** [zigalenarcic/mangl#2]
- hi, I make **mangl** binary file on ubuntu [18.04.3] budgie, it works but send warnings as follow:
in **mandoc/roff.c**
![captura](https://user-images.githubusercontent.com/2924638/66704304-2ccd6b00-ece0-11e9-8ada-45ed8b3d2a64.png)
in **main.c**
![captura_1](https://user-images.githubusercontent.com/2924638/66704312-35be3c80-ece0-11e9-8928-1007780706f7.png)

- ## and... to return to the main window I didn't see there is an option

**Comment by zigalenarcic** [comment]
Thank you. I've fixed the warnings. The command to go to search screen is: Ctrl-f. I've written this in README.md.

**Comment by zeroidentidad** [comment]
oh, I see ... you're welcome, thanks bro
