### ISSUE TITLE
Hyperlinks don't work when manual page specified on the command line

### ISSUE THREAD

**Issue by ibara** [zigalenarcic/mangl#5]
Hi --

We noticed this making the OpenBSD package of mangl.
If you start mangl with the name of a manual page on the command line (e.g., "mangl ls") and go down to the SEE ALSO section, the hyperlinks don't work. But if you start mangl by itself then search for the ls manual page and go down to SEE ALSO, the hyperlinks do work.

**Comment by zigalenarcic** [comment]
Should be fixed now. Thank you for observing and reporting the bug.

**Comment by ibara** [comment]
That works; I've already updated the OpenBSD package. Thanks for the quick fix!

**Comment by zigalenarcic** [comment]
Thank you for making the OpenBSD package.
