### ISSUE TITLE
Automatic page width

### ISSUE THREAD

**Issue by vaygr** [zigalenarcic/mangl#8]
In tiling window managers it's common that app window is maximized resulting in awkward-looking manpage display by mangl.

I wonder if it'd be easy to make manpage width automatic based on the window width.

![shot-2022-09-24_201634](https://user-images.githubusercontent.com/8810597/192126774-6f41182b-3bbb-41b5-b018-50791ea88220.png)

**Comment by christian-burger** [comment]
In that regard I'd like to point out that there is an ["optimal" line length for convenient reading](https://en.wikipedia.org/wiki/Line_length). And it seems to me, that mangl fits that criteria.

Maybe just center the whole block instead? Might look less awkward. :shrug: 

Or: When there is enough width: Show multiple columns. Though I guess, that's a pretty heavy feature with a lot of side effects, complicating the matter very much.

**Comment by zigalenarcic** [comment]
In v1.1.3 there is now automatic centering of the text. The number of characters in a line (78) however is still fixed due to the reason mentioned by @christian-burger - long lines are harder to read.
If necessary I can add an option (either in settings or as a key command) to change the line length.

**Comment by zigalenarcic** [comment]
I've added support for:
* line_length value in config file
* = shortcut key on manpage display to automatically adjust the line length to match the current window width

I think it will help with these issues.

**Comment by vaygr** [comment]
This is excellent @zigalenarcic, thanks. Tested, works as expected. Maybe it makes sense to add a shortcut to get back to default view or have <kbd>=</kbd> as a toggle?

**Comment by zigalenarcic** [comment]
Hi
I made it toggle the width in commit 0f3db125ea3e385ac07b69fc1a505049c06cf165
