### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by yochananmarqos** [zigalenarcic/mangl#9]
I just tried building from the latest commit on Manjaro GNOME using the following:

```
cd mandoc
./configure --prefix=/usr
make -C ..
```

It didn't make it very far... (pun not intended, heh)

```
file config.log: writing...
make: echo: No such file or directory
make: *** [/tmp/GmK0okaP:2: all] Error 127
```

**Comment by zigalenarcic** [comment]
Please check if it works with commit b4d00ce

**Comment by yochananmarqos** [comment]
Yes, that did the trick. Thanks!
